[2025-06-25T03:40:20.455+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-25T03:40:20.514+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clinlytix360_pipeline.run_etl_cleaning manual__2025-06-25T03:39:55.881905+00:00 [queued]>
[2025-06-25T03:40:20.533+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clinlytix360_pipeline.run_etl_cleaning manual__2025-06-25T03:39:55.881905+00:00 [queued]>
[2025-06-25T03:40:20.536+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-06-25T03:40:20.568+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): run_etl_cleaning> on 2025-06-25 03:39:55.881905+00:00
[2025-06-25T03:40:20.588+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=393) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-06-25T03:40:20.592+0000] {standard_task_runner.py:63} INFO - Started process 402 to run task
[2025-06-25T03:40:20.591+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'clinlytix360_pipeline', 'run_etl_cleaning', 'manual__2025-06-25T03:39:55.881905+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/clinlytix_dag.py', '--cfg-path', '/tmp/tmp45m8663e']
[2025-06-25T03:40:20.606+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask run_etl_cleaning
[2025-06-25T03:40:20.837+0000] {task_command.py:426} INFO - Running <TaskInstance: clinlytix360_pipeline.run_etl_cleaning manual__2025-06-25T03:39:55.881905+00:00 [running]> on host 34096c58d0ef
[2025-06-25T03:40:21.302+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='ajayc' AIRFLOW_CTX_DAG_ID='clinlytix360_pipeline' AIRFLOW_CTX_TASK_ID='run_etl_cleaning' AIRFLOW_CTX_EXECUTION_DATE='2025-06-25T03:39:55.881905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-25T03:39:55.881905+00:00'
[2025-06-25T03:40:21.317+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-25T03:40:21.326+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-25T03:40:21.333+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/data/scripts/etl/etl_cleaning.py']
[2025-06-25T03:40:21.387+0000] {subprocess.py:86} INFO - Output:
[2025-06-25T03:40:29.405+0000] {subprocess.py:93} INFO - 
[2025-06-25T03:40:29.409+0000] {subprocess.py:93} INFO - ðŸ©º Cleaning ehr_oncology.csv...
[2025-06-25T03:40:29.414+0000] {subprocess.py:93} INFO - âœ… Survival days match follow-up correctly.
[2025-06-25T03:40:29.416+0000] {subprocess.py:93} INFO - 
[2025-06-25T03:40:29.422+0000] {subprocess.py:93} INFO - ðŸ“‹ Cleaning trial_protocol.csv...
[2025-06-25T03:40:29.425+0000] {subprocess.py:93} INFO - âœ… Trial protocol cleaned successfully.
[2025-06-25T03:40:29.427+0000] {subprocess.py:93} INFO - 
[2025-06-25T03:40:29.429+0000] {subprocess.py:93} INFO - ðŸ§  Cleaning pro_scores.csv...
[2025-06-25T03:40:29.431+0000] {subprocess.py:93} INFO - âœ… PRO scores clean.
[2025-06-25T03:40:29.437+0000] {subprocess.py:93} INFO - 
[2025-06-25T03:40:29.442+0000] {subprocess.py:93} INFO - âœ… All datasets cleaned and saved successfully.
[2025-06-25T03:40:29.941+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-06-25T03:40:29.945+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-25T03:40:30.105+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=clinlytix360_pipeline, task_id=run_etl_cleaning, execution_date=20250625T033955, start_date=20250625T034020, end_date=20250625T034030
[2025-06-25T03:40:30.252+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-25T03:40:30.377+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-06-25T03:40:30.383+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
